### ISSUE TITLE
AbstractBusFactory attachPlugins uses hardcoded vendor name iso using vendorName()

### ISSUE THREAD

**Issue by DannyvdSluijs** [prooph/service-bus#102]
At https://github.com/prooph/service-bus/blob/master/src/Container/AbstractBusFactory.php#L128 a hard coded vendor name is used in stead of the function vendorName().

When implementing the abstract bus factory and overloading vendorName() the exception would be incorrect.

**Comment by sandrokeil** [comment]
@DannyvdSluijs You're right. Do you want to make a pull request please?
