### ISSUE TITLE
EventRouter catch-all

### ISSUE THREAD

**Issue by jpkleemans** [prooph/service-bus#125]
Is there a way to listen to all events? For example to log all events.

Something like:
```php
$router->route('*')->to($listener);
```

**Comment by prolic** [comment]
You can use a plugin to achieve that.

**Comment by prolic** [comment]
Implementation details see f.e. here:

https://github.com/prooph/service-bus/blob/master/src/Plugin/MessageProducerPlugin.php

**Comment by jpkleemans** [comment]
Ah, thanks!
