### ISSUE TITLE
QueryBus: yield response instead of return promise

### ISSUE THREAD

**Issue by codeliner** [prooph/service-bus#127]
@bweston92 some time ago you've mentioned  that there is maybe a way to replace promises with generators in the query bus to avoid callbacks.
I'd like to discuss this option for the planed major release. At the moment I'm not sure if this will work.
Do you have a concrete idea?

**Comment by bweston92** [comment]
@codeliner eithers (https://github.com/JosephMoniz/php-either)

```
/**
 * @param QueryBus $queryBus
 * @param Query $withQuery
 * @return Either
 */
function query_bus_with(QueryBus $queryBus, Query $withQuery)
{
    $queryBus->dispatch($withQuery)->done(function ($data) use (&$response) {
        $response = new Right($data);
    }, function ($error) use (&$response) {
        $response = new Left($error);
    });

    return $response;
}
```

**Comment by prolic** [comment]
I think this is not worth is, bascially it's the same approach. Can we close this?

**Comment by bweston92** [comment]
Is actually means you don't have to have nested callbacks. But yeah this can be achieved by using a hacky yield implementation.

**Comment by codeliner** [comment]
I'm fine with closing it. @bweston92 your example looks cool. :+1: for the functional style
