### ISSUE TITLE
UnauthorizedException not informative

### ISSUE THREAD

**Issue by basz** [prooph/service-bus#136]
Would it be bad to have its name present. These messages aren't useful while developing. I realise that may expose information, but I think I may want to do that anyway (I want 403 returned)

```
Prooph\ServiceBus\Plugin\Guard\UnauthorizedException: You are not authorized to access this resource
```

**Comment by prolic** [comment]
You want to show what? The class name or the event name?

Am 02.09.2016 06:20 schrieb "Bas Kamer" <notifications@github.com>:

**Comment by basz** [comment]
I would say name of the denied thing. Classnames of commands

**Comment by prolic** [comment]
A command does not need to be a classname, see: https://github.com/prooph/service-bus/blob/master/src/CommandBus.php#L62
