### ISSUE TITLE
Get rid of the AbstractInvokeStrategy

### ISSUE THREAD

**Issue by prolic** [prooph/service-bus#152]
We should get rid of the `AbstractInvokeStrategy`, the only class extending it is the `HandleCommandStrategy`, so there is no need for this abstraction.

**Comment by codeliner** [comment]
but the `AbstractInvokeStrategy` should make it easy to define a userland strategy (from the docs):
>  If your favorite convention is not there you can easily write your own invoke strategy by extending Prooph\ServiceBus\Plugin\InvokeStrategy\AbstractInvokeStrategy and implementing the canInvoke and invoke methods.

**Comment by prolic** [comment]
@basz extended it today to create a custom OnEventStrategy, and ran into
troubles, because it uses handler instead of listeners. The strategy has
only like 20 lines of code. Building a custom one is no problem without the
abstract class.

Am 14.01.2017 01:31 schrieb "Alexander Miertsch" <notifications@github.com>:

**Comment by codeliner** [comment]
ok
