### ISSUE TITLE
Exception in event listener stops propagating event to other registered listeners 

### ISSUE THREAD

**Issue by Averor** [prooph/service-bus#165]
It seems, that in version 6 it is not possible to propagate event in event-listeners, when one of them throws an exception. Resetting EVENT_PARAM_EXCEPTION allows us to handle thrown exception (log it or whatever) thus stop it from bubbling back to the app, but it won't help to continue with invoking the rest of registered listeners.

**Comment by codeliner** [comment]
If @prolic is not faster I can check the issue in 3-4 hours. Should be possible to catch exceptions and continue with the rest of the listeners, but maybe we've introduced a bug by cleaning up the message dispatch process. Thx for the bug report

**Comment by codeliner** [comment]
@Averor fix is on the way ^^
