### ISSUE TITLE
QueryBus returns null with FinalizeGuard plugin included

### ISSUE THREAD

**Issue by lezhnev74** [prooph/service-bus#177]
Test to reproduce the problem:
https://github.com/lezhnev74/prooph-query-test/blob/prooph-bare/tests/QueryTest.php

Results:
- executing query with no guards - pass
- executing query with `RouteGuard` - pass
- executing query with `FinalizeGuard` - **fail**

**Comment by basz** [comment]
promises are suppose to return something. each then() may change the passed payload.

therefore when I change the FinalizeGuard like the following, I get three green lights when running your tests.

```
$newPromise = $promise->then(function ($result) use ($actionEvent, $messageName) {
                        if (! $this->authorizationService->isGranted($messageName, $result)) {
                            $actionEvent->stopPropagation(true);

                            if (! $this->exposeEventMessageName) {
                                $messageName = '';
                            }

                            throw new UnauthorizedException($messageName);
                        }

                        return $result; // note this, but also the return type has changed
                    });

                    $actionEvent->setParam(QueryBus::EVENT_PARAM_PROMISE, $newPromise);
```

I don't understand why this would have worked so far. I'm using the same react/promise version.

**Comment by basz** [comment]
https://blog.domenic.me/youre-missing-the-point-of-promises/

**Comment by lezhnev74** [comment]
I don't deal with async stuff at my work. Is something I should make a PR for or what is the solution here?

@basz can you take a moment and analyze your code. If you will copy the same tests in your project - will they fail? If so hows your project working? :)
