### ISSUE TITLE
exchange PromiseInterface for ExtendedPromiseInterface

### ISSUE THREAD

**Issue by basz** [prooph/service-bus#179]
Could we exchange \React\Promise\PromiseInterface for \React\Promise\ExtendedPromiseInterface which simply extends PromiseInterface but has the done method? see https://reactphp.org/promise/#extendedpromiseinterface

until #147 anyway

**Comment by prolic** [comment]
that's a BC break, but we can do this in next major release.

**Comment by basz** [comment]
should we have a dev branch for the next major version?

**Comment by basz** [comment]
next release will solve this: https://github.com/reactphp/promise/blob/master/CHANGELOG.md

keeping open so we don't forget

**Comment by prolic** [comment]
New branch is not needed at the moment. We just leave this ticket open and
collect a few ideas. I do not have any deep plans about new major releases
at the moment.

**Comment by basz** [comment]
> next release will solve this ...

clarification: the next release of *reactphp/promise*. 

In the new version ExtendedPromiseInterface's methods are merged into PromiseInterface. Therefore the issue I raised will become void at some point in time.

**Comment by fritz-gerneth** [comment]
Just stumpled across this issue for the same reason as @basz . 

Any way curious if @prolic 's work on v8 event store will affect this implementation here too? I know amp can adapt react promises. Still would be better to have one promise implementation throughout the library?

**Comment by prolic** [comment]
I think it's better to leave react promise here. Because amp can adapt it,
you can use this library with amp AND you can also use it with reactphp.
