### ISSUE TITLE
What the sense in ReactPHP  and it is Promises if QueryBus works synchronously?

### ISSUE THREAD

**Issue by BonBonSlick** [prooph/service-bus#189]
I have tested 2 queries 

```
`$this->queryBus->dispatch(new GetUserList( ))->then(
            function($result){
                dump($result); // some result
            }
        );

        $this->queryBus->dispatch( new GetUserList( ))->then(
            function($result)  {
                dump($result); // empty should be
            }
        )
        ;`
```

for first one handler i put sleep for 5 seconds, and here results are

```
//first - should be last, coz results + sleep
Paginator {#3327 ▼
...
}
//second, should be first, because no sleep + empty results
[]
```

Maybe i missed something, please tell me please.

**Comment by prolic** [comment]
see https://github.com/prooph/service-bus/blob/master/tests/QueryBusTest.php

Sascha-Oliver Prolic

2018-06-30 2:43 GMT+08:00 BonBonSlick <notifications@github.com>:

**Comment by BonBonSlick** [comment]
@prolic thank you for your response, i still do not get it. What should i note?

**Comment by prolic** [comment]
You can wrap the query bus with your own implementation, so that you wrap the promise and return the real value. This should be very easy to write in a few minutes. I think someone posted the implementation for this already somewhere, but I can't remember.

About the initial question, I think you should use `done()` and not `then()` - see https://sergeyzhuk.me/2017/06/16/phpreact-promises/

**Comment by fritz-gerneth** [comment]
https://github.com/reactphp/promise/issues/43 for a similar question. E.g. you have to make the async code yourself. For synchronous code the promise is still synchronous too.

**Comment by BonBonSlick** [comment]
@prolic Method 'done' not found in \React\Promise\PromiseInterface less... (Ctrl+F1 Alt+T) 
Referenced method is not found in subject class.

**Comment by fritz-gerneth** [comment]
`done` is only a part of of `PromiseInterface` since v3. Before this ([v2](https://github.com/reactphp/promise/tree/2.x)) it was part of the `ExtendedPromiseInterface`. When you'll return a `Promise`, it will both interfaces though.

**Comment by BonBonSlick** [comment]
Thank you for clarification. 
I think it would be nice idea to add some extra examples for bus and event. Sync / async, and how to write tests for these features. Also add more info from https://github.com/reactphp/promise or at least some give some links to point where people should search.

**Comment by prolic** [comment]
@BonBonSlick @codeliner wanna provide some docs? otherwise it's just another issue sitting here for years :)

**Comment by BonBonSlick** [comment]
It is ok, we changed to symfony messenger. Use only your store everything else written from scratch
