### ISSUE TITLE
CommandRouter class missed onRouteCommand method.

### ISSUE THREAD

**Issue by prolic** [prooph/service-bus#51]
See failing tests:

method Prooph\ServiceBus\Router\CommandRouter::onRouteCommand not found.

see: https://travis-ci.org/prooph/proophessor/jobs/64147997

Additional: Shouldn't the query-router have a onRouteQuery method?

**Comment by codeliner** [comment]
proophessor test is fixed. See prooph/proophessor#25

I've changed the implementation due to the new QueryRouter. Command- and QueryRouter share the same base class SingleTargetRouter which now has a method onRouteMessage.

**Comment by prolic** [comment]
Great. Thanks.
